# Site settings
title: Danielle Chen Porfolio
email: daniellemchen@gmail.com
description: Welcome to my personal porfolio! > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dchen.github.io" # the base hostname & protocol for your site

linkedin_username: daniellemchen
github_username: daniellemchen

# Build settings
markdown: kramdown
